# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import os
import pathlib
import typing
__all__ = [
    "combine_fits",
    "extract_plane_from_cube",
]

def combine_fits(file_list: typing.Sequence[builtins.str | os.PathLike | pathlib.Path], out_cube: builtins.str | os.PathLike | pathlib.Path, spec_file: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None, spec_list: typing.Optional[typing.Sequence[builtins.float]] = None, ignore_spec: builtins.bool = False, create_blanks: builtins.bool = False, overwrite: builtins.bool = False, max_workers: typing.Optional[builtins.int] = None, time_domain_mode: builtins.bool = False, bounding_box: builtins.bool = False, invalidate_zeros: builtins.bool = False, float_length: typing.Optional[builtins.int] = None) -> builtins.list[builtins.float]:
    r"""
    Combine single-plane FITS images into a cube.
    
    Args:
        file_list (list[str]): Paths of the FITS images to combine.
        out_cube (str): Output cube path.
        spec_file (str, optional): File of frequencies (Hz) / times (MJD s),
            one per line. Mutually exclusive with ``spec_list``.
        spec_list (list[float], optional): Frequencies/times supplied directly.
            Mutually exclusive with ``spec_file``.
        ignore_spec (bool): Ignore frequency/time info and just stack.
        create_blanks (bool): Interpolate an evenly-spaced axis, blanking gaps.
        overwrite (bool): Overwrite the output cube if it exists.
        max_workers (int, optional): Concurrency bound for in-flight planes.
        time_domain_mode (bool): Combine along time (DATE-OBS) instead of FREQ.
        bounding_box (bool): Trim blank padding via a common bounding box.
        invalidate_zeros (bool): Treat exactly-zero pixels as NaN.
        float_length (int, optional): Output precision in bits (32 or 64).
    
    Returns:
        list[float]: The output-axis values (Hz for frequency, MJD s for time).
    
    Raises:
        ValueError: On invalid input or a FITS error.
    """

def extract_plane_from_cube(fits_cube: builtins.str | os.PathLike | pathlib.Path, channel_index: typing.Optional[builtins.int] = None, time_index: typing.Optional[builtins.int] = None, hdu_index: builtins.int = 0, overwrite: builtins.bool = False, output_path: typing.Optional[builtins.str | os.PathLike | pathlib.Path] = None) -> builtins.str:
    r"""
    Extract a single plane (channel or timestep) from a FITS cube.
    
    Args:
        fits_cube (str): The cube to extract from.
        channel_index (int, optional): Frequency channel to extract. Mutually
            exclusive with ``time_index``.
        time_index (int, optional): Timestep to extract. Mutually exclusive with
            ``channel_index``.
        hdu_index (int): HDU index of the cube data (default 0).
        overwrite (bool): Overwrite the output file if it exists.
        output_path (str, optional): Output path; generated from the cube name
            if omitted.
    
    Returns:
        str: Path of the written plane image.
    
    Raises:
        ValueError: On invalid options or a FITS error.
    """

